#!/bin/bash
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
#export XDG_CURRENT_DESKTOP=wlr

export MOZ_ENABLE_WAYLAND=1

exec dbus-run-session sway --unsupported-gpu
