#!/usr/bin/env bash

readonly CONFIG_DIR="${HOME}/.config"
readonly CONFIG_SUBMODULES="${CONFIG_DIR}/submodules"
readonly BASHRC="${HOME}/.bashrc"

install_shell_config() {
    echo '' >> "${BASHRC}"
    # shellcheck disable=SC2016
    echo 'export PATH="${PATH}:${HOME}/.local/bin"' >> "${BASHRC}"
    mkdir -p "${HOME}/.local/bin"

    echo '' >> "${BASHRC}"
    echo "eval \$(dircolors "${CONFIG_SUBMODULES}/dircolors-solarized/dircolors.ansi-dark")" \
        >> "${BASHRC}"

    local -r alacritty_dir="${CONFIG_DIR}/alacritty"
    local -r alacritty_config="${alacritty_dir}/alacritty.yml"
    mkdir -p "${alacritty_dir}"
    touch "${alacritty_config}"
    cat "${CONFIG_SUBMODULES}/alacritty-theme/themes/solarized_dark.yaml" >> "${alacritty_config}"

    cat << EOF >> "${BASHRC}"

SSH_ENV_FILE="/${HOME}/.ssh/.agent.env"
if ! pgrep ssh-agent > /dev/null; then
    ssh-agent | grep -v 'echo' > "${SSH_ENV_FILE}"
fi
source "${SSH_ENV_FILE}"
unset SSH_ENV_FILE
if ! ssh-add -lq > /dev/null; then
    ssh-add
fi
EOF
}

install_system_config() {
    cp "${CONFIG_DIR}/misc/45-backlight.rules" /etc/udev/rules.d/
    cp "${CONFIG_DIR}/sway/sway-nvidia.desktop" /usr/share/wayland-sessions/
}

install_editor_config() {
    local -r editor=nvim

    echo '' >> "${BASHRC}"
    echo "EDITOR=${editor}" >> "${BASHRC}"
    echo "SUDO_EDITOR=${editor}" >> "${BASHRC}"
    echo "alias vim=${editor}" >> "${BASHRC}"

    git config --global core.editor "${editor}"
}

install_git_config() {
    git config --global user.name "Steven Sloboda"

    git config --global commit.gpgsign true
    git config --global core.excludesfile "${CONFIG_DIR}/misc/gitignore_global"
}

main() {
    pushd "${CONFIG_DIR}"

    git sumbodule update --init --recursive

    install_shell_config
    install_editor_config
    install_git_config

    popd
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -ex
    main "$@"
fi
